package Cryptopracticals;

/**
 * @author vemvmacpro
 * This is for Practical 1/task 1 for the ISBN + Credit card 
 */
public class Task1 extends javax.swing.JFrame {

    /**
     *  Creates new form NewJFrame and I renamed to Task 1
     */
    
   
    public Task1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("verify ISBN");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("verify Credit Card");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Clear");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("ISBN ");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel2.setText("Credit Card ");

        jButton4.setText("run methods");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane2.setViewportView(jTextArea2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(41, 41, 41)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(28, 28, 28))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)))
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jButton3)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jButton4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * This will verify the ISBN number in the 1st text field
     */
    //Examples of ISBN
    //99921-58-10-7 - this will give a valid
    //960-425-059-0 - this will give a valid
    //1-84356-028-3 - this will give a valid
    //99921-58-10-3 - this will give an invalid

    private void ISBN()
    {
        int[] digits = new int[16];
        String s;
        
        int result = 0;
        int error_check;
        
        jTextArea1.setText("");
        
        s = jTextField1.getText();
        
        // Text will print out if the length is not equal to 10 digits 
                        
        if(10 != s.length())
        {
            jTextArea1.setText("Please enter a 10 digit number!"); 
            return;
        }
        
        
        for (int i = 8; i >= 0; i--) 
        {
            digits[i] = Integer.parseInt(String.valueOf(s.charAt(i)));

            if (i >= 9) {
                continue;
            }
            result += digits[i] * (i+1);
        }

        if (s.charAt(9) != 'x') {
            error_check = Integer.parseInt(String.valueOf(s.charAt(9)));
        } else {
            error_check = 10;
        }

                
        // Here are print statements 
        System.out.println(result);
        System.out.println("error check is: "+error_check);
        System.out.println("Mod is:"+ result % 11 +" result is: "+ result);
        
        
        //if the result is more than 11 then invalid ISBN will print, if not, then prints out a valid ISBN
        
        if (result % 11 == error_check) {
            jTextArea1.setText("This is a valid ISBN");
        } else {
            jTextArea1.setText("This is an invalid ISBN, please enter a valid one!");
        }
    }
    
    // verifies credit card number in the second text field
    // An example to test is 5555 5555 5555 4444 - this will give a valid
    // Another example to test is 4552 7204 1234 5698  - this will give an invalid
    
    
    private void CreditCard()
    {
        String s; // credit card string
        int[] d = new int[20]; // credit card will be parsed int array
        int outcome = 0; 

        // This will pull in the credit card string
        s = jTextField2.getText();
        
        // if statement to check if it is a 16 digit number
        if(s.length() != 16)
        {
            jTextArea1.setText("Please enter a 16 digit number");   
            return;
        }
            
        // for each number in credit card, this will be verified 
        for (int n = 0; n < 16; n++) 
        {
            int temporary; 
            
            d[n] = Integer.parseInt(String.valueOf(s.charAt(n)));
            
            if (n % 2 == 0) {
                temporary = d[n]*2;
            } else {
                temporary = d[n];
            }
            
            
            if (temporary < 10) {
            } else {
                temporary -= 9;
            }
            
            // Credit card numbers will be collected
            outcome += temporary;
           
        }
        
        System.out.println("modulo of result is: "+outcome%10);
        
        // If the end outcome is divisible by 10 with no remainder is will be valid.
        if (outcome % 10 != 0) {
            jTextArea1.setText("This is a invalid credit card!");
        } else {
            jTextArea1.setText("This a valid credit card!");
        }
    }
    
    
    
   // The code below is an extention that was part of worksheet 1, this will be 
   // used to test and calculate the results of all 3 mod functions with test values
    

   // Regarding to modular arithmetic, this will return the inverse of the number, 
   // all of this is from the lecture 2 slide using Euclidean Algorithm
    
    public int inverse(int a, int modulo) 
    { 
        
    int t = 0; 
    int newt = 1; 
    int r = modulo; 
    int newr = a;    
    int q, temporary;  

    if (newr != 0) {
            do {
                q = r / newr; // integer division  
                temporary = newt; // remember newt is put into a temporary 
                newt = t - q * newt;
                t = temporary;
                temporary = newr; // remember newr is put into a temporary
                newr = r - q * newr;
                r = temporary;
            } while (newr != 0);
        } 
    
    if (r <= 1) {
            if (t < 0) t = t + modulo; // change to positive 
            return t;
        } else {
            return -1; // This is not invertible 
        }
    
    }
    
    //This will add both numbers and the mod 11
    
   public int add_mod11(int x, int y)
   {
       return ((((x+y)%11)+11)%11);
   }
  
   
    //This will  multiply both numbers and the mod 11
   
    public int multiply_mod11(int x, int y)
   {
  
       return ((((x*y)%11)+11)%11);
   }
    
    
     //This will invert and mutiply with mod 11 
       
    public int invert_mod11(int x, int y)
   {
       
        int a = ((x*y)%11);
        
        if (a >= 0) {
           return a;
       } else {
            int p = 0;
            while(inverse(p,11)!=(inverse(a,11)))p++;
            return p;
       }

   }
    
    
     // This will show the outcome of all 3 modulo functions 
     
    private void outcome_mod()
    {
        jTextArea2.setText("add: " + add_mod11(-3,8) + "\n" +
                            "multiply: " + multiply_mod11(-3,8) + "\n" + 
                            "invert: " + invert_mod11(-3,8));
    }
    
    
    // This helps it clear the text fields and text area
     
    private void clear_user_interface()
    {
        jTextField1.setText("");
        jTextField2.setText("");
        jTextArea1.setText("");
        jTextArea2.setText("");
    }
    
    
    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ISBN();
    }//GEN-LAST:event_jButton1MouseClicked

    
    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        clear_user_interface();
    }//GEN-LAST:event_jButton3MouseClicked

    
    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        CreditCard();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        outcome_mod();
    }//GEN-LAST:event_jButton4MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Task1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
